### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by serchavalos** [loociano/gb-ES6#1]
Hey Luciano!

I got this error in the console when I tried to executed by uploading this rom
https://github.com/loociano/gb-ES6/blob/master/roms/blargg_cpu_instrs.gb

<img width="839" alt="skarmavbild 2016-09-29 kl 23 29 38" src="https://cloud.githubusercontent.com/assets/587388/18973200/aab9ba1c-869c-11e6-8b56-8accac8342b0.png">

Should I tried with another file?

**Comment by loociano** [comment]
Hi @serchavalos, thanks for reporting! That's a testing ROM I will support shortly. At the moment only Tetris works (can't share the game here as it is copyrighted).

**Comment by loociano** [comment]
This has been fixed in 0.0.18

All Blargg's CPU instructions test are now passing :)
https://github.com/loociano/gb-ES6/blob/master/roms/blargg/cpu_instrs/cpu_instrs.gb

![](https://raw.githubusercontent.com/loociano/gb-ES6/master/screenshots/2017-01-29%2023_08_51-gb-ES6.png)
